# Generated by Django 4.1.6 on 2023-02-20 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("directory_items", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="directoryitem",
            old_name="source_url",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="directoryitem",
            old_name="item_name",
            new_name="name",
        ),
    ]
