# Generated by Django 4.1.6 on 2023-02-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("fileUrl", models.TextField()),
                ("category", models.CharField(max_length=140)),
                ("description", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
