# Generated by Django 4.1.6 on 2023-02-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="fileUrl",
            new_name="file_URL",
        ),
    ]
